export const categoryColor = [
  { color: "red", colorName: "Red" },
  { color: "blue", colorName: "Blue" },
  { color: "green", colorName: "Green" },
  { color: "yellow", colorName: "Yellow" },
  { color: "purple", colorName: "Purple" },
  { color: "orange", colorName: "Orange" },
  { color: "pink", colorName: "Pink" },
  { color: "brown", colorName: "Brown" },
  { color: "black", colorName: "Black" },
  { color: "white", colorName: "White" },
  { color: "grey", colorName: "Grey" },
  { color: "cyan", colorName: "Cyan" },
  { color: "magenta", colorName: "Magenta" },
  { color: "lime", colorName: "Lime" },
  { color: "maroon", colorName: "Maroon" },
];
